version: "3.8"
services:
  # vscode
  vscode:
    image: mcr.microsoft.com/vscode/devcontainers/dotnet:0-6.0-bullseye-slim
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/vscode/.dotnet/tools
    # don't shutdown container if it's fails
    command: [
        "/bin/sh",
        "-c",
        "cd /workspace/ && umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install lts/* 2>&1 && cd /workspace/ && umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install lts/* 2>&1 && dotnet restore && dotnet dev-certs https && npm install && while sleep 1000; do :; done"
      ]
    # command: ["/bin/sh", "-c", "while sleep 1000; do :; done"]
    user: vscode
    volumes:
      - ..:/workspace:cached
    networks:
      - network
    hostname: vscode
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    networks:
      - network
networks:
  network:
